import { DCC, DEX, INIT } from "./defaults";
import type { Deal } from "./types";

// Built-in Atlanta example deals. `col` is a CSS-var token string (presentation reads it).
export interface Example extends Partial<Deal> {
  id: string; label: string; sub: string; tag: string; col: string;
}

export const EXAMPLES: Example[] = [
  { id: "en", label: "English Ave", sub: "SW ATL · C/D", tag: "Disaster", col: "var(--c-red)", address: "English Ave, Atlanta, GA 30314", notes: "Distressed SW Atlanta block. Below-market rents but deferred maintenance, high vacancy and crime drag. Riskier-area financing pushes the rate higher. NOI can't cover the mortgage — a money pit unless bought all-cash at a deep discount.", price: 250000, units: [{ id: 1, label: "Unit 1", rent: 700, beds: 2, bath: 1, sqft: 780 }, { id: 2, label: "Unit 2", rent: 700, beds: 2, bath: 1, sqft: 780 }, { id: 3, label: "Unit 3", rent: 650, beds: 1, bath: 1, sqft: 560 }, { id: 4, label: "Unit 4", rent: 650, beds: 1, bath: 1, sqft: 560 }], financing: { downPct: 25, rate: 8.75, loanYears: 30 }, closing: { ...DCC, quickPct: 3 }, expenses: { ...DEX, mode: "quick", ratio: 56, vacancyPct: 14, propertyClass: "C" }, projection: { ...INIT.projection, appreciationPct: 1, rentGrowthPct: 1 }, repairs: { include: false, unknown: true, amount: 0 }, partnership: { ...INIT.partnership }, comparables: [] },
  { id: "cp", label: "College Park", sub: "South ATL · C", tag: "Bad", col: "var(--c-red)", address: "College Park, GA 30337", notes: "Near the airport, steady C-class demand. Priced too high for the rents it produces — cap rate sits below the mortgage rate, so it bleeds cash every month. Lender DSCR also falls short of 1.0. Needs a price cut to work.", price: 410000, units: [{ id: 1, label: "Unit 1", rent: 1150, beds: 2, bath: 1, sqft: 880 }, { id: 2, label: "Unit 2", rent: 1150, beds: 2, bath: 1, sqft: 880 }, { id: 3, label: "Unit 3", rent: 1050, beds: 1, bath: 1, sqft: 680 }, { id: 4, label: "Unit 4", rent: 1050, beds: 1, bath: 1, sqft: 680 }], financing: { downPct: 25, rate: 7.5, loanYears: 30 }, closing: { ...DCC, quickPct: 3 }, expenses: { ...DEX, mode: "quick", ratio: 49, vacancyPct: 8, propertyClass: "C" }, projection: { ...INIT.projection, appreciationPct: 2.5, rentGrowthPct: 2 }, repairs: { include: false, unknown: false, amount: 0 }, partnership: { ...INIT.partnership }, comparables: [] },
  { id: "cl", label: "Clarkston", sub: "DeKalb · B−", tag: "Mixed", col: "var(--c-amber)", address: "Clarkston, GA 30021", notes: "Stable, diverse DeKalb rental market with reliable demand. Roughly breaks even today with a thin DSCR — the return is mostly a bet on modest appreciation and rent growth. Workable but no margin for error.", price: 520000, units: [{ id: 1, label: "Unit 1", rent: 1500, beds: 2, bath: 1, sqft: 930 }, { id: 2, label: "Unit 2", rent: 1500, beds: 2, bath: 1, sqft: 930 }, { id: 3, label: "Unit 3", rent: 1325, beds: 1, bath: 1, sqft: 700 }, { id: 4, label: "Unit 4", rent: 1325, beds: 1, bath: 1, sqft: 700 }], financing: { downPct: 25, rate: 7.25, loanYears: 30 }, closing: { ...DCC, quickPct: 3 }, expenses: { ...DEX, mode: "quick", ratio: 45, vacancyPct: 6, propertyClass: "B" }, projection: { ...INIT.projection, appreciationPct: 3.2, rentGrowthPct: 3 }, repairs: { include: false, unknown: false, amount: 0 }, partnership: { ...INIT.partnership }, comparables: [] },
  { id: "sm", label: "Smyrna", sub: "Cobb · B+", tag: "Good", col: "var(--c-teal)", address: "Smyrna, GA 30080", notes: "Strong Cobb County submarket — low vacancy, good schools, steady appreciation. Bought at a fair price with a relationship rate, it clears a 1.2 DSCR and cash-flows from day one. A solid, financeable hold.", price: 620000, units: [{ id: 1, label: "Unit 1", rent: 1800, beds: 2, bath: 1, sqft: 950 }, { id: 2, label: "Unit 2", rent: 1800, beds: 2, bath: 1, sqft: 950 }, { id: 3, label: "Unit 3", rent: 1550, beds: 1, bath: 1, sqft: 700 }, { id: 4, label: "Unit 4", rent: 1550, beds: 1, bath: 1, sqft: 700 }], financing: { downPct: 25, rate: 6.9, loanYears: 30 }, closing: { ...DCC, quickPct: 3 }, expenses: { ...DEX, mode: "quick", ratio: 42, vacancyPct: 5, propertyClass: "B" }, projection: { ...INIT.projection, appreciationPct: 4, rentGrowthPct: 3.5 }, repairs: { include: false, unknown: false, amount: 0 }, partnership: { ...INIT.partnership }, comparables: [] },
  { id: "kw", label: "Kirkwood", sub: "Intown · Value-add", tag: "Home run", col: "var(--c-teal)", address: "Kirkwood, Atlanta, GA 30317", notes: "Off-market intown fourplex with below-market rents and light cosmetic needs. Bought right, it already cash-flows and clears every metric. Turn the units and push rents to market (≈$2,050) for forced appreciation and a true home run.", price: 550000, units: [{ id: 1, label: "Unit 1", rent: 1850, beds: 2, bath: 1, sqft: 950 }, { id: 2, label: "Unit 2", rent: 1850, beds: 2, bath: 1, sqft: 950 }, { id: 3, label: "Unit 3", rent: 1600, beds: 1, bath: 1, sqft: 680 }, { id: 4, label: "Unit 4", rent: 1600, beds: 1, bath: 1, sqft: 680 }], financing: { downPct: 25, rate: 6.75, loanYears: 30 }, closing: { ...DCC, quickPct: 3.5 }, expenses: { ...DEX, mode: "quick", ratio: 40, vacancyPct: 5, propertyClass: "B" }, projection: { ...INIT.projection, appreciationPct: 5, rentGrowthPct: 4, vaEnabled: true, vaMarketRentPerUnit: 2050, vaYear: 2 }, repairs: { include: true, unknown: false, amount: 25000 }, partnership: { ...INIT.partnership }, comparables: [] },
];
